### ISSUE TITLE
Conflicts with webpack

### ISSUE THREAD

**Issue by stanleychuwu** [Luavis/moment-lunar#2]
I'm installing this via npm, and I get this error when I import the library in my main file to try to use it.

WARNING in ./~/moment-lunar/moment-lunar.js
12:48-55 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

This is what my import statements look like.

import React from 'react';
import moment from 'moment'
import lunar from 'moment-lunar'
console.log(moment().lunar())

I'm using webpack and I do have moment.js already installed

**Comment by Luavis** [comment]
Hi, I just checked this plugin is not supporting webpack.
So, I updated it to work with webpack well and, supporting typescript. (version 0.0.4)

Please check new updates, and you need to import moment-lunar like following.

```js
import React from 'react';
import moment from 'moment';
import 'moment-lunar';
console.log(moment().lunar());
```

please leave comment if you have any questions.
Thanks.
